import Navbar from '@/components/Navbar'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>pk</title>
        <meta name='description' content='generated by create next app' />
        <meta name='viewport' content='width=device-width , initial-scale=1' />
        <link rel="icon" href='/P.ico' />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  )
}
